# Generated by Django 4.2.3 on 2023-09-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_question_type_useranswer_quizprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='marks',
            new_name='score',
        ),
    ]
