# Generated by Django 4.2.3 on 2023-09-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_useranswer_selected_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='marks_obtained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_input',
            field=models.TextField(blank=True, null=True),
        ),
    ]
