# Generated by Django 4.2.3 on 2023-09-22 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_useranswer_marks_obtained_useranswer_user_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='questions_info',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='quiz_attempted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.category'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
