# Generated by Django 4.2.3 on 2023-09-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_useranswer_questions_info_useranswer_quiz_attempted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
