# Generated by Django 4.2.3 on 2023-09-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_useranswer_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='questions_info',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='quiz_attempted',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='total_score',
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
