# Generated by Django 4.2.3 on 2023-09-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_useranswer_questions_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_quizzes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
