# Generated by Django 4.2.3 on 2023-09-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_user_completed_quizzes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='completed_quizzes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
