# Generated by Django 4.2.3 on 2023-09-26 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_userresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='category',
        ),
    ]
