# Generated by Django 4.2.3 on 2023-09-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_remove_userresponse_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
